In [122]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [123]:
data=pd.read_csv(r'Churn_Modelling (1).csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [124]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [125]:
lable_encoder=LabelEncoder()
onehot_encoder=OneHotEncoder()

In [126]:
data['Gender']=lable_encoder.fit_transform(data['Gender'])
data['Gender']

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int32

In [127]:
geo_onehot_encoded=onehot_encoder.fit_transform(data[['Geography']]).toarray()

In [128]:
geo_onehot_encoder_df = pd.DataFrame(
    geo_onehot_encoded,
    columns=onehot_encoder.get_feature_names_out(['Geography'])
)

In [129]:
df=pd.concat([data.drop('Geography',axis=1),geo_onehot_encoder_df],axis=1)

In [130]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [131]:
X=df.drop('EstimatedSalary',axis=1)
y=df['EstimatedSalary']

In [132]:
with open('lable_encoder_gender.pkl','wb') as file:
    pickle.dump('lable_encoder_gender',file)
with open('onehot_encoder_geography.pkl','wb') as file:
    pickle.dump('onehot_encoder_geography',file)
with open('scaler.pkl','wb') as file:
    pickle.dump('scaler',file)

In [133]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

In [134]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [135]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [136]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

ANN Classification

In [137]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [138]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

In [139]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

In [140]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                832

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [141]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [142]:
tensorflow_callback = tensorflow.keras.callbacks.TensorBoard(log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S"), histogram_freq=1)

In [143]:
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [144]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=25,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/25

250/250 [==============================] - 2s 6ms/step - loss: 13383080960.0000 - mae: 100374.6484 - val_loss: 13004951552.0000 - val_mae: 98507.9141
Epoch 2/25
250/250 [==============================] - 1s 5ms/step - loss: 13227507712.0000 - mae: 99603.1953 - val_loss: 12695127040.0000 - val_mae: 96943.0625
Epoch 3/25
250/250 [==============================] - 1s 4ms/step - loss: 12679631872.0000 - mae: 96868.6484 - val_loss: 11906885632.0000 - val_mae: 92956.0547
Epoch 4/25
250/250 [==============================] - 1s 4ms/step - loss: 11596464128.0000 - mae: 91511.1484 - val_loss: 10587170816.0000 - val_mae: 86284.7344
Epoch 5/25
250/250 [==============================] - 1s 4ms/step - loss: 10026407936.0000 - mae: 83674.0938 - val_loss: 8883948544.0000 - val_mae: 77744.2031
Epoch 6/25
250/250 [==============================] - 2s 6ms/step - loss: 8191314432.0000 - mae: 74474.0781 - val_loss: 7085640704.0000 - val_mae: 68764.1953
Epoch 7/25
250/250 [==============================] - 2s 7ms/step - loss: 6429232640.0000 - mae: 65592.9609 - val_loss: 5531737600.0000 - val_mae: 61023.0078
Epoch 8/25
250/250 [==============================] - 2s 7ms/step - loss: 5044640256.0000 - mae: 58515.2031 - val_loss: 4466034688.0000 - val_mae: 55635.9062
Epoch 9/25
250/250 [==============================] - 2s 7ms/step - loss: 4166109184.0000 - mae: 53991.9414 - val_loss: 3874650624.0000 - val_mae: 52601.1797
Epoch 10/25
250/250 [==============================] - 2s 7ms/step - loss: 3716491008.0000 - mae: 51622.0000 - val_loss: 3620901888.0000 - val_mae: 51332.5234
Epoch 11/25
250/250 [==============================] - 2s 7ms/step - loss: 3529206016.0000 - mae: 50645.3594 - val_loss: 3530371840.0000 - val_mae: 50884.3828
Epoch 12/25
250/250 [==============================] - 2s 7ms/step - loss: 3457672704.0000 - mae: 50309.7930 - val_loss: 3494640640.0000 - val_mae: 50715.7148
Epoch 13/25
250/250 [==============================] - 2s 8ms/step - loss: 3425520896.0000 - mae: 50139.1328 - val_loss: 3475166208.0000 - val_mae: 50615.9609
Epoch 14/25
250/250 [==============================] - 1s 6ms/step - loss: 3407005440.0000 - mae: 50057.2656 - val_loss: 3459534848.0000 - val_mae: 50532.0039
Epoch 15/25
250/250 [==============================] - 2s 7ms/step - loss: 3393758464.0000 - mae: 49985.3086 - val_loss: 3446762752.0000 - val_mae: 50467.7461
Epoch 16/25
250/250 [==============================] - 2s 6ms/step - loss: 3382664192.0000 - mae: 49935.5898 - val_loss: 3436488960.0000 - val_mae: 50418.2461
Epoch 17/25
250/250 [==============================] - 1s 5ms/step - loss: 3373645312.0000 - mae: 49889.8711 - val_loss: 3427423232.0000 - val_mae: 50376.3516
Epoch 18/25
250/250 [==============================] - 1s 5ms/step - loss: 3365983232.0000 - mae: 49857.6641 - val_loss: 3417842432.0000 - val_mae: 50330.6133
Epoch 19/25
250/250 [==============================] - 1s 5ms/step - loss: 3359428096.0000 - mae: 49816.9023 - val_loss: 3411653888.0000 - val_mae: 50304.2656
Epoch 20/25
250/250 [==============================] - 1s 4ms/step - loss: 3353723136.0000 - mae: 49793.5859 - val_loss: 3406432768.0000 - val_mae: 50280.5156
Epoch 21/25
250/250 [==============================] - 1s 5ms/step - loss: 3348167168.0000 - mae: 49764.3359 - val_loss: 3400671488.0000 - val_mae: 50255.9688
Epoch 22/25
250/250 [==============================] - 1s 4ms/step - loss: 3343800320.0000 - mae: 49742.7148 - val_loss: 3395795200.0000 - val_mae: 50234.3867
Epoch 23/25
250/250 [==============================] - 1s 5ms/step - loss: 3339526656.0000 - mae: 49721.6914 - val_loss: 3391851264.0000 - val_mae: 50221.6172
Epoch 24/25
250/250 [==============================] - 1s 5ms/step - loss: 3336073472.0000 - mae: 49704.8164 - val_loss: 3386884864.0000 - val_mae: 50198.1836
Epoch 25/25
250/250 [==============================] - 1s 5ms/step - loss: 3333150976.0000 - mae: 49689.8750 - val_loss: 3383002624.0000 - val_mae: 50182.1758

In [145]:
# loading tensorflow
%load_ext tensorboard

In [146]:
%tensorboard --logdir regressionlogs/fit

In [147]:
model.save('regression.h5')

d:\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(